import { Contact, Property, Opportunity, Activity, User } from '@/types';

// Simulazione database in-memory (in produzione usare un vero database)
export const db = {
  users: [
    {
      id: '1',
      name: 'Mario Rossi',
      email: 'mario.rossi@immobiliare.it',
      role: 'admin' as const,
      branch: 'Torino Centro',
      active: true,
      createdAt: '2024-01-15T10:00:00Z',
    },
    {
      id: '2',
      name: 'Laura Bianchi',
      email: 'laura.bianchi@immobiliare.it',
      role: 'agent' as const,
      branch: 'Torino Centro',
      active: true,
      createdAt: '2024-02-01T10:00:00Z',
    },
  ] as User[],

  contacts: [
    {
      id: '1',
      type: 'person' as const,
      name: 'Giovanni',
      surname: 'Verdi',
      fiscalCode: 'VRDGNN80A01L219K',
      phone: '+39 345 1234567',
      email: 'giovanni.verdi@email.it',
      address: 'Via Roma 15, Torino',
      roles: ['buyer' as const],
      source: 'Sito web',
      referentAgent: '2',
      privacyConsent: true,
      privacyConsentDate: '2024-11-01T10:00:00Z',
      notes: 'Interessato ad appartamenti zona centro storico',
      tags: ['Alta priorità', 'Primo acquisto'],
      createdAt: '2024-11-01T10:00:00Z',
      updatedAt: '2024-11-15T14:30:00Z',
    },
    {
      id: '2',
      type: 'person' as const,
      name: 'Maria',
      surname: 'Neri',
      fiscalCode: 'NREMRA75D50L219Y',
      phone: '+39 348 7654321',
      email: 'maria.neri@email.it',
      address: 'Corso Francia 88, Torino',
      roles: ['owner' as const],
      source: 'Passaparola',
      referentAgent: '1',
      privacyConsent: true,
      privacyConsentDate: '2024-10-15T10:00:00Z',
      notes: 'Proprietaria appartamento da vendere',
      tags: ['VIP'],
      createdAt: '2024-10-15T10:00:00Z',
      updatedAt: '2024-11-20T09:15:00Z',
    },
    {
      id: '3',
      type: 'company' as const,
      companyName: 'Investimenti Immobiliari SRL',
      vatNumber: '12345678901',
      phone: '+39 011 1234567',
      email: 'info@investimentiimm.it',
      address: 'Via Milano 45, Torino',
      roles: ['investor' as const],
      source: 'LinkedIn',
      referentAgent: '1',
      privacyConsent: true,
      privacyConsentDate: '2024-09-01T10:00:00Z',
      notes: 'Interessati a immobili commerciali per investimento',
      tags: ['Investitore', 'Portafoglio ampio'],
      createdAt: '2024-09-01T10:00:00Z',
      updatedAt: '2024-11-10T16:45:00Z',
    },
  ] as Contact[],

  properties: [
    {
      id: '1',
      internalCode: 'TO-001-2024',
      address: 'Via Garibaldi 45',
      city: 'Torino',
      province: 'TO',
      zipCode: '10122',
      lat: 45.0703,
      lng: 7.6869,
      type: 'residential' as const,
      category: 'apartment' as const,
      cadastralData: {
        sheet: '234',
        parcel: '1567',
        sub: '12',
        category: 'A/2',
      },
      surface: 95,
      rooms: 4,
      bedrooms: 2,
      bathrooms: 1,
      floor: 3,
      totalFloors: 5,
      yearBuilt: 1920,
      energyClass: 'E',
      heating: 'Centralizzato',
      condition: 'Buono',
      features: ['Ascensore', 'Balcone', 'Cantina'],
      monthlyExpenses: 120,
      price: 245000,
      status: 'available' as const,
      visibility: 'public' as const,
      exclusive: true,
      mandateDate: '2024-10-01T10:00:00Z',
      mandateExpiry: '2025-04-01T10:00:00Z',
      description: 'Elegante appartamento in pieno centro storico, in palazzo d\'epoca completamente ristrutturato. Composto da ingresso, soggiorno, cucina abitabile, due camere da letto e bagno. Riscaldamento centralizzato, ascensore, cantina.',
      images: ['/images/properties/1-1.jpg', '/images/properties/1-2.jpg'],
      ownerId: '2',
      agentId: '1',
      createdAt: '2024-10-01T10:00:00Z',
      updatedAt: '2024-11-25T11:20:00Z',
    },
    {
      id: '2',
      internalCode: 'TO-002-2024',
      address: 'Corso Vittorio Emanuele II 120',
      city: 'Torino',
      province: 'TO',
      zipCode: '10121',
      type: 'commercial' as const,
      category: 'shop' as const,
      surface: 80,
      floor: 0,
      yearBuilt: 1950,
      energyClass: 'F',
      condition: 'Da ristrutturare',
      features: ['Vetrina', 'Bagno', 'Magazzino'],
      price: 1200,
      status: 'available' as const,
      visibility: 'public' as const,
      exclusive: false,
      mandateDate: '2024-11-01T10:00:00Z',
      mandateExpiry: '2025-05-01T10:00:00Z',
      description: 'Locale commerciale in zona di grande passaggio, ideale per attività commerciali. Composto da ampio spazio vendita con vetrina, bagno e magazzino.',
      images: ['/images/properties/2-1.jpg'],
      agentId: '2',
      createdAt: '2024-11-01T10:00:00Z',
      updatedAt: '2024-11-20T14:30:00Z',
    },
    {
      id: '3',
      internalCode: 'TO-003-2024',
      address: 'Via Po 88',
      city: 'Torino',
      province: 'TO',
      zipCode: '10124',
      type: 'residential' as const,
      category: 'apartment' as const,
      surface: 120,
      rooms: 5,
      bedrooms: 3,
      bathrooms: 2,
      floor: 5,
      totalFloors: 6,
      yearBuilt: 1970,
      energyClass: 'D',
      heating: 'Autonomo',
      condition: 'Ottimo',
      features: ['Ascensore', 'Terrazzo', 'Cantina', 'Box auto'],
      monthlyExpenses: 150,
      price: 380000,
      status: 'available' as const,
      visibility: 'public' as const,
      exclusive: true,
      mandateDate: '2024-09-15T10:00:00Z',
      mandateExpiry: '2025-03-15T10:00:00Z',
      description: 'Luminoso attico con terrazzo panoramico vista Po. Completamente ristrutturato con finiture di pregio. Zona giorno open space, tre camere matrimoniali, doppi servizi. Box auto e cantina.',
      images: ['/images/properties/3-1.jpg', '/images/properties/3-2.jpg', '/images/properties/3-3.jpg'],
      agentId: '2',
      createdAt: '2024-09-15T10:00:00Z',
      updatedAt: '2024-11-18T09:45:00Z',
    },
  ] as Property[],

  opportunities: [
    {
      id: '1',
      type: 'sale' as const,
      propertyId: '1',
      contactId: '1',
      agentId: '2',
      stage: 'proposal' as const,
      status: 'active' as const,
      probability: 70,
      expectedValue: 245000,
      expectedCloseDate: '2024-12-31T10:00:00Z',
      notes: 'Cliente molto interessato, in attesa di risposta su proposta presentata',
      createdAt: '2024-11-10T10:00:00Z',
      updatedAt: '2024-11-26T15:30:00Z',
    },
    {
      id: '2',
      type: 'rental' as const,
      propertyId: '2',
      contactId: '3',
      agentId: '2',
      stage: 'visit' as const,
      status: 'active' as const,
      probability: 40,
      expectedValue: 14400,
      expectedCloseDate: '2024-12-15T10:00:00Z',
      notes: 'Visita effettuata, in attesa di feedback',
      createdAt: '2024-11-15T10:00:00Z',
      updatedAt: '2024-11-22T11:15:00Z',
    },
    {
      id: '3',
      type: 'sale' as const,
      propertyId: '3',
      contactId: '3',
      agentId: '2',
      stage: 'qualified' as const,
      status: 'active' as const,
      probability: 30,
      expectedValue: 380000,
      notes: 'Primo contatto positivo, da programmare visita',
      createdAt: '2024-11-20T10:00:00Z',
      updatedAt: '2024-11-25T10:00:00Z',
    },
  ] as Opportunity[],

  activities: [
    {
      id: '1',
      type: 'visit' as const,
      title: 'Visita appartamento Via Garibaldi',
      description: 'Prima visita con Giovanni Verdi',
      contactId: '1',
      propertyId: '1',
      opportunityId: '1',
      assignedTo: '2',
      scheduledDate: '2024-11-12T15:00:00Z',
      completedDate: '2024-11-12T15:45:00Z',
      duration: 45,
      outcome: 'Cliente molto interessato, apprezza posizione e stato. Vuole presentare proposta.',
      status: 'completed' as const,
      createdAt: '2024-11-10T10:00:00Z',
      updatedAt: '2024-11-12T16:00:00Z',
    },
    {
      id: '2',
      type: 'call' as const,
      title: 'Follow-up proposta',
      description: 'Chiamata per aggiornamento su proposta presentata',
      contactId: '1',
      opportunityId: '1',
      assignedTo: '2',
      scheduledDate: '2024-11-28T10:00:00Z',
      status: 'planned' as const,
      createdAt: '2024-11-26T14:00:00Z',
      updatedAt: '2024-11-26T14:00:00Z',
    },
    {
      id: '3',
      type: 'visit' as const,
      title: 'Visita locale commerciale Corso Vittorio',
      description: 'Sopralluogo con rappresentante Investimenti Immobiliari SRL',
      contactId: '3',
      propertyId: '2',
      opportunityId: '2',
      assignedTo: '2',
      scheduledDate: '2024-11-29T14:30:00Z',
      status: 'planned' as const,
      createdAt: '2024-11-25T09:00:00Z',
      updatedAt: '2024-11-25T09:00:00Z',
    },
    {
      id: '4',
      type: 'meeting' as const,
      title: 'Incontro per acquisizione nuovo immobile',
      description: 'Primo incontro con proprietario per valutazione',
      contactId: '2',
      assignedTo: '1',
      scheduledDate: '2024-11-30T11:00:00Z',
      status: 'planned' as const,
      createdAt: '2024-11-27T16:30:00Z',
      updatedAt: '2024-11-27T16:30:00Z',
    },
  ] as Activity[],
};

// Helper per generare nuovi ID
let idCounter = 100;
export const generateId = (): string => {
  idCounter++;
  return idCounter.toString();
};
